### ISSUE TITLE
Source Files Couldn't be Found!!

### ISSUE THREAD

**Issue by ParkerSM** [mixradio/.net-sdk#5]
![one](https://cloud.githubusercontent.com/assets/11041896/6389645/e2c234ee-bdb6-11e4-8976-7c759db93fe4.PNG)

**Comment by srgb** [comment]
Opps, sorry about that, this is what happens when I add features over Christmas and new year.
I've pushed the missing files, pulled and built the project, so hopefully it's OK now, please let me know,
Steve
